
site_name: aioworxmower Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
nav:
  - Home: index.md
  - User Guide:
      - Quickstart: user/quickstart.md
      - Debugging: user/debugging.md
      - Fixtures: user/fixtures.md
      - Realtime: user/realtime.md
  - Developer Guide:
      - Architecture: dev/architecture.md
      - Providers: dev/providers.md
      - Testing: dev/testing.md
      - CI/CD: dev/ci_cd.md
plugins:
  - awesome-pages
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
