name: Docs Sync

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: docs
          sparse-checkout-cone-mode: false

      - name: Push Markdown docs to Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/tb-killa/aioworxmower-docs.wiki.git wiki-repo
          rsync -av --delete docs/ wiki-repo/
          cd wiki-repo
          git config user.email "ci@example.com"
          git config user.name "CI Bot"
          git add .
          git commit -m "sync docs → wiki" || echo "No changes"
          git push

  build-html:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-html')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build docs
        run: poetry run mkdocs build --strict
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
